version: '3.7'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=my_db
    ports:
      - '5438:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  recorder:
    build:
      dockerfile: Dockerfile
      context: .
    command:
      - --dbDSN=postgres://user:passwd@postgres:5432/my_db
    ports:
      - '8080:8080'