name: Go Integration Test
on: [push, pull_request]

jobs:
  integration:
    name: Postgres
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: passwd
          POSTGRES_USER: user
          POSTGRES_DB: LassieEvents
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"
      - name: Run integration tests with race detector
        run: go test -v -race --tags=integration ./...
